### ISSUE TITLE
Bugs in the search bar and the right sidebar

### ISSUE THREAD

**Issue by CHADREX** [spider-themes/eazydocs#1]
Introductions:
PHP 7.4
Fresh WP
Theme: Twenty Twenty-Two and Blocksy

1. Search behaves strangely, records are found without problems, but the items in the drop-down list are not clickable.
2. Nothing appears in the sidebar (content), despite the titles in the documentation.
3. Probably the search keywords do not work either (in the trial pro-version), not in any way.

**Comment by CHADREX** [comment]
2. Fixed
\wp-content\plugins\eazydocs\includes\Frontend\Assets.php:55
`wp_enqueue_script( 'bootstrap-toc', EAZYDOCS_ASSETS . '/js/frontend/bootstrap-toc.min.js', array('jquery','bootstrap') );`
to
`wp_enqueue_script( 'bootstrap-toc', EAZYDOCS_ASSETS . '/js/frontend/bootstrap-toc.min.js', array('jquery'), $version );`

**Comment by CHADREX** [comment]
1. Fixed

\wp-content\plugins\eazydocs\assets\js\frontend\docs-single.js:581
Replace:
` $("#ezd_searchInput").focusout(function() {`
to
`$(".focus_overlay").click(function() {`

**Comment by mdjwel** [comment]
Thanks for your suggestions. We will update the plugin based on your suggestions
